version: '3.4'

services:

### Cinnox-Homework ##################################
  homework:
    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - "80:80"

    depends_on:
      - mongodb

### MongoDB ##################################
  mongodb:
    image: mongo:4.4
    restart: always

    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root

    volumes:
      - ./data:/data/db

    ports:
      - 27017:27017